server {
    listen 127.0.0.1:8080;

    client_max_body_size 10m;

    error_page 404 /tester2/error_pages/404.html;

    location / {
        allow_methods GET POST DELETE;
        root ./tester2/www;
        index index.html;
        autoindex on;
    }

    location /noindex {
        allow_methods GET;
        root ./tester2/www/noindex;
        autoindex off;
    }

    location /getonly {
        allow_methods GET;
        root ./tester2/www/getonly;
    }

    location /noupload {
        allow_methods GET POST;
        root ./tester2/www/noupload;
    }

    location /old-site {
        return 301 /;
    }

    location /upload {
        allow_methods GET POST DELETE;
        root ./tester2/uploads;
        autoindex on;
        upload_enable on;
        upload_store ./tester2/uploads/files;
    }
}

server {
    listen 127.0.0.1:8081;

    client_max_body_size 20;

    error_page 404 /tester2/error_pages/404.html;

    location / {
        allow_methods GET POST;
        root ./tester2/www;
        index index.html;
        upload_enable on;
        upload_store ./tester2/uploads/files;
    }
}
