server {
    listen 127.0.0.1:8092;
    client_max_body_size 200;

    location / {
        allow_methods GET;
        root ./www/html;
        index index.html;
    }
    location /directory {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        cgi_extension .bla;
        cgi_pass /workspaces/webserv/cgi_tester;
    }
    location /post_body {
        allow_methods POST;
        root ./www;
    }
}
